### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by alvaro-paco** [KSDaemon/sails-hook-sequelize#24]
I couldn't create a transaction with this sequelize instance. How can i use sequelize transactions with sails-hook-sequelize?

**Comment by malpercio** [comment]
You have `sequelize` as a global variable.

```js
```

**Comment by KSDaemon** [comment]
Hi @alvaro-paco! @malpercio had given answer. So, closing for now. Feel free to reopen if you face any problems

**Comment by jhnferraris** [comment]
Is this still work on Sails 1.0? I'm getting `transaction is not a function`.

```
sails> sequelize.transaction()
TypeError: sequelize.transaction is not a function

```

This is the output when I try to run it on `sails console`

Thanks for the help.

**Comment by jhnferraris** [comment]
If anyone of you is using SailsJS 1.0, this is what I did

```
SequelizeConnections.default.transaction(transaction => {
// Your transaction
})
```

assuming that `default` is the key in your `sails.config.datastores`

```
datastores: {
    default: {
      adapter: require("sails-postgresql"),
      database: "your_db",
      user: "your_user",
      password: "<your_password>",
      ssl: false,
      options: {
        dialect: "postgres",
        host: "<localhost>",
        port: 5432,
        logging: console.log,
      }
    }
  },

```
